enable_language(C)
add_library(LVGL
        middleware/lv_conf.h
        middleware/lvgl/lvgl.h
        middleware/lvgl/src/lv_version.h
        middleware/lvgl/src/lv_font/lv_font.h
        middleware/lvgl/src/lv_font/lv_font_roboto_12.c
        middleware/lvgl/src/lv_font/lv_font_roboto_28.c
        middleware/lvgl/src/lv_font/lv_font_unscii_8.c
        middleware/lvgl/src/lv_font/lv_font.c
        middleware/lvgl/src/lv_font/lv_font_fmt_txt.h
        middleware/lvgl/src/lv_font/lv_font_roboto_16.c
        middleware/lvgl/src/lv_font/lv_symbol_def.h
        middleware/lvgl/src/lv_font/lv_font_roboto_22.c
        middleware/lvgl/src/lv_font/lv_font_fmt_txt.c
        middleware/lvgl/src/lv_hal/lv_hal.h
        middleware/lvgl/src/lv_hal/lv_hal_indev.c
        middleware/lvgl/src/lv_hal/lv_hal_disp.c
        middleware/lvgl/src/lv_hal/lv_hal_disp.h
        middleware/lvgl/src/lv_hal/lv_hal_indev.h
        middleware/lvgl/src/lv_hal/lv_hal_tick.h
        middleware/lvgl/src/lv_hal/lv_hal_tick.c
        middleware/lvgl/src/lv_misc/lv_circ.c
        middleware/lvgl/src/lv_misc/lv_task.h
        middleware/lvgl/src/lv_misc/lv_anim.c
        middleware/lvgl/src/lv_misc/lv_area.h
        middleware/lvgl/src/lv_misc/lv_fs.h
        middleware/lvgl/src/lv_misc/lv_fs.c
        middleware/lvgl/src/lv_misc/lv_math.h
        middleware/lvgl/src/lv_misc/lv_mem.c
        middleware/lvgl/src/lv_misc/lv_log.c
        middleware/lvgl/src/lv_misc/lv_math.c
        middleware/lvgl/src/lv_misc/lv_txt.c
        middleware/lvgl/src/lv_misc/lv_anim.h
        middleware/lvgl/src/lv_misc/lv_gc.c
        middleware/lvgl/src/lv_misc/lv_txt.h
        middleware/lvgl/src/lv_misc/lv_color.c
        middleware/lvgl/src/lv_misc/lv_async.c
        middleware/lvgl/src/lv_misc/lv_circ.h
        middleware/lvgl/src/lv_misc/lv_gc.h
        middleware/lvgl/src/lv_misc/lv_utils.c
        middleware/lvgl/src/lv_misc/lv_task.c
        middleware/lvgl/src/lv_misc/lv_area.c
        middleware/lvgl/src/lv_misc/lv_types.h
        middleware/lvgl/src/lv_misc/lv_mem.h
        middleware/lvgl/src/lv_misc/lv_color.h
        middleware/lvgl/src/lv_misc/lv_templ.c
        middleware/lvgl/src/lv_misc/lv_utils.h
        middleware/lvgl/src/lv_misc/lv_templ.h
        middleware/lvgl/src/lv_misc/lv_ll.h
        middleware/lvgl/src/lv_misc/lv_log.h
        middleware/lvgl/src/lv_misc/lv_async.h
        middleware/lvgl/src/lv_misc/lv_ll.c
        middleware/lvgl/src/lv_objx/lv_canvas.h
        middleware/lvgl/src/lv_objx/lv_ta.h
        middleware/lvgl/src/lv_objx/lv_lmeter.c
        middleware/lvgl/src/lv_objx/lv_mbox.h
        middleware/lvgl/src/lv_objx/lv_tabview.h
        middleware/lvgl/src/lv_objx/lv_kb.c
        middleware/lvgl/src/lv_objx/lv_btnm.h
        middleware/lvgl/src/lv_objx/lv_tileview.h
        middleware/lvgl/src/lv_objx/lv_mbox.c
        middleware/lvgl/src/lv_objx/lv_page.h
        middleware/lvgl/src/lv_objx/lv_ddlist.h
        middleware/lvgl/src/lv_objx/lv_label.h
        middleware/lvgl/src/lv_objx/lv_spinbox.c
        middleware/lvgl/src/lv_objx/lv_slider.c
        middleware/lvgl/src/lv_objx/lv_line.h
        middleware/lvgl/src/lv_objx/lv_slider.h
        middleware/lvgl/src/lv_objx/lv_led.c
        middleware/lvgl/src/lv_objx/lv_objx_templ.h
        middleware/lvgl/src/lv_objx/lv_win.c
        middleware/lvgl/src/lv_objx/lv_img.h
        middleware/lvgl/src/lv_objx/lv_objx_templ.c
        middleware/lvgl/src/lv_objx/lv_tabview.c
        middleware/lvgl/src/lv_objx/lv_gauge.c
        middleware/lvgl/src/lv_objx/lv_arc.h
        middleware/lvgl/src/lv_objx/lv_ta.c
        middleware/lvgl/src/lv_objx/lv_led.h
        middleware/lvgl/src/lv_objx/lv_imgbtn.c
        middleware/lvgl/src/lv_objx/lv_table.c
        middleware/lvgl/src/lv_objx/lv_canvas.c
        middleware/lvgl/src/lv_objx/lv_cb.c
        middleware/lvgl/src/lv_objx/lv_lmeter.h
        middleware/lvgl/src/lv_objx/lv_sw.h
        middleware/lvgl/src/lv_objx/lv_spinbox.h
        middleware/lvgl/src/lv_objx/lv_table.h
        middleware/lvgl/src/lv_objx/lv_list.c
        middleware/lvgl/src/lv_objx/lv_chart.h
        middleware/lvgl/src/lv_objx/lv_roller.c
        middleware/lvgl/src/lv_objx/lv_win.h
        middleware/lvgl/src/lv_objx/lv_calendar.c
        middleware/lvgl/src/lv_objx/lv_bar.h
        middleware/lvgl/src/lv_objx/lv_preload.h
        middleware/lvgl/src/lv_objx/lv_roller.h
        middleware/lvgl/src/lv_objx/lv_preload.c
        middleware/lvgl/src/lv_objx/lv_arc.c
        middleware/lvgl/src/lv_objx/lv_calendar.h
        middleware/lvgl/src/lv_objx/lv_tileview.c
        middleware/lvgl/src/lv_objx/lv_gauge.h
        middleware/lvgl/src/lv_objx/lv_label.c
        middleware/lvgl/src/lv_objx/lv_cont.h
        middleware/lvgl/src/lv_objx/lv_kb.h
        middleware/lvgl/src/lv_objx/lv_cont.c
        middleware/lvgl/src/lv_objx/lv_btn.h
        middleware/lvgl/src/lv_objx/lv_btnm.c
        middleware/lvgl/src/lv_objx/lv_sw.c
        middleware/lvgl/src/lv_objx/lv_cb.h
        middleware/lvgl/src/lv_objx/lv_list.h
        middleware/lvgl/src/lv_objx/lv_btn.c
        middleware/lvgl/src/lv_objx/lv_page.c
        middleware/lvgl/src/lv_objx/lv_img.c
        middleware/lvgl/src/lv_objx/lv_imgbtn.h
        middleware/lvgl/src/lv_objx/lv_ddlist.c
        middleware/lvgl/src/lv_objx/lv_bar.c
        middleware/lvgl/src/lv_objx/lv_line.c
        middleware/lvgl/src/lv_objx/lv_chart.c
        middleware/lvgl/src/lv_draw/lv_draw_triangle.h
        middleware/lvgl/src/lv_draw/lv_draw_rect.c
        middleware/lvgl/src/lv_draw/lv_draw_line.c
        middleware/lvgl/src/lv_draw/lv_img_decoder.c
        middleware/lvgl/src/lv_draw/lv_draw_line.h
        middleware/lvgl/src/lv_draw/lv_img_cache.h
        middleware/lvgl/src/lv_draw/lv_draw_basic.h
        middleware/lvgl/src/lv_draw/lv_draw_basic.c
        middleware/lvgl/src/lv_draw/lv_draw_arc.h
        middleware/lvgl/src/lv_draw/lv_draw_label.c
        middleware/lvgl/src/lv_draw/lv_draw.c
        middleware/lvgl/src/lv_draw/lv_draw_rect.h
        middleware/lvgl/src/lv_draw/lv_draw.h
        middleware/lvgl/src/lv_draw/lv_draw_img.h
        middleware/lvgl/src/lv_draw/lv_draw_triangle.c
        middleware/lvgl/src/lv_draw/lv_draw_label.h
        middleware/lvgl/src/lv_draw/lv_img_decoder.h
        middleware/lvgl/src/lv_draw/lv_draw_img.c
        middleware/lvgl/src/lv_draw/lv_img_cache.c
        middleware/lvgl/src/lv_draw/lv_draw_arc.c
        middleware/lvgl/src/lv_conf_checker.h
        middleware/lvgl/src/lv_themes/lv_theme_nemo.h
        middleware/lvgl/src/lv_themes/lv_theme_alien.c
        middleware/lvgl/src/lv_themes/lv_theme_alien.h
        middleware/lvgl/src/lv_themes/lv_theme_zen.h
        middleware/lvgl/src/lv_themes/lv_theme_night.h
        middleware/lvgl/src/lv_themes/lv_theme_night.c
        middleware/lvgl/src/lv_themes/lv_theme_nemo.c
        middleware/lvgl/src/lv_themes/lv_theme_zen.c
        middleware/lvgl/src/lv_themes/lv_theme.h
        middleware/lvgl/src/lv_themes/lv_theme_material.c
        middleware/lvgl/src/lv_themes/lv_theme_templ.c
        middleware/lvgl/src/lv_themes/lv_theme.c
        middleware/lvgl/src/lv_themes/lv_theme_mono.c
        middleware/lvgl/src/lv_themes/lv_theme_mono.h
        middleware/lvgl/src/lv_themes/lv_theme_default.h
        middleware/lvgl/src/lv_themes/lv_theme_default.c
        middleware/lvgl/src/lv_themes/lv_theme_templ.h
        middleware/lvgl/src/lv_themes/lv_theme_material.h
        middleware/lvgl/src/lv_core/lv_group.h
        middleware/lvgl/src/lv_core/lv_refr.c
        middleware/lvgl/src/lv_core/lv_indev.h
        middleware/lvgl/src/lv_core/lv_disp.h
        middleware/lvgl/src/lv_core/lv_refr.h
        middleware/lvgl/src/lv_core/lv_style.c
        middleware/lvgl/src/lv_core/lv_group.c
        middleware/lvgl/src/lv_core/lv_disp.c
        middleware/lvgl/src/lv_core/lv_style.h
        middleware/lvgl/src/lv_core/lv_obj.h
        middleware/lvgl/src/lv_core/lv_indev.c
        middleware/lvgl/src/lv_core/lv_obj.c
        )
target_compile_options(LVGL PRIVATE
        ${TARGET_SPECIFIC_FLAGS}
        ${ADDITIONAL_CXX_FLAGS}
        ${CXX_WARN_FLAGS})
target_link_options(LVGL PRIVATE
        ${LINKER_FLAGS}
        ${ADDITIONAL_LINKER_FLAGS})
